AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String

Resources:
  UpdateCloudfrontSG:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: 
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Policies:
        - LambdaInvokePolicy:
          FunctionName:
            Ref: FunctionNameParam
        - Version: '2012-10-17' # Security Group Policy Document
                Statement:
                  - Effect: Allow
                    Action:
                      - ec2:RevokeSecurityGroupIngress
                      - ec2:AuthorizeSecurityGroupIngress
                    Resource: 'arn:aws:ec2:*:*:security-group/*'
                  - Effect": "Allow",
                    Action:
                      - ec2:DescribeSecurityGroupReferences
                      - ec2:DescribeTags
                      - ec2:DescribeSecurityGroups
                    Resource: "*"
      Description: ''
      MemorySize: 128
      Timeout: 60
      Events:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged
